### ISSUE TITLE
Get all cached keys

### ISSUE THREAD

**Issue by nightscape** [onionskin/onionskin#10]
Hi!

In some cases it would be very handy to be able to list all cached keys. A user could then e.g. decide that he wants to get the cached data instead of waiting for non-cached data to load.

I'm not sure if this is at all possible, i.e. if all drivers support such an option, an alternative would be a special key (e.g. '/**keys**') which lists all the cached keys and gets updated with every cache put.

Best
  Martin

**Comment by tadeuzagallo** [comment]
Sorry for the really long time to respond, some complications on my end.

I currently use keys methods on all drivers, but as mentioned on #8, using keys is a bad practice, and a really slow method. I should implement purge, in order to stop using keys methods.

Isn't [cache policies](http://onionskin.io/api/#onionskin-item-cachepolicies) what you want?

``` js
pool.get('key', OnionSkin.CP_OLD, function() {
  // this will just trigger if no cached data is available
});
```

But anyway I think you can do exactly what you said, with two nested access, may not be the ideal for you, but might work... something like:

``` js
pool.get('first_key', function() { 
  // first_key is not cached
  return pool.get('second_key', function () {
    // if second_key is not cached, request new data
    return requestNewData();
  };
});
```

Let me know if it's what you meant, and again, sorry for the long time.

**Comment by nightscape** [comment]
Hi tadeuzagallo,

in the meanwhile I've experimented a lot with client-side caching and it doesn't work well with the amount of data I have (100+MB).
My original request was maybe not too well explained so I'll try again (although I don't need it anymore now):
I have lots of datasets from test runs of an algorithm stored on the server. Let's say the test runs are numbered from 1 to 6. Users don't have to look at all test runs, it's often sufficient to pick a subset.
Say a user had already looked at runs 1,4 and 5. I would have liked to highlight those runs in the selection list of runs, so the user can see that those runs would already be available in the browser without needing to access the server:

```
1 ✔
2
3
4 ✔
5 ✔
6
```

For this it would have been convenient to be able to retrieve all cached keys (= runs in my case) from onionskin.

As I already switched to server-side caching due to sheer data size, there's nothing to do here and I'll close the ticket.

Thanks anyways!
  Martin
